# Generated by Django 4.1.3 on 2023-05-26 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=32, verbose_name='first name')),
                ('mname', models.CharField(blank=True, max_length=32, null=True, verbose_name='middle name')),
                ('lname', models.CharField(blank=True, max_length=32, null=True, verbose_name='last name')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('act', 'active'), ('inc', 'inactive'), ('del', 'delete')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('act', 'active'), ('inc', 'inactive'), ('del', 'delete')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ManyToManyField(blank=True, to='descansa.author')),
            ],
        ),
        migrations.CreateModel(
            name='BookReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('act', 'active'), ('inc', 'inactive'), ('del', 'delete')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descansa.book')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=32)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('act', 'active'), ('inc', 'inactive'), ('del', 'delete')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=64, null=True)),
                ('current_status', models.CharField(choices=[('10', 'started'), ('11', 'halfway or more'), ('12', 'finished'), ('13', 'cancelled'), ('14', 'paused'), ('15', 'restarted'), ('21', 'planned')], max_length=16)),
                ('status', models.CharField(choices=[('act', 'active'), ('inc', 'inactive'), ('del', 'delete')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('reading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='descansa.bookreading')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='descansa.tag'),
        ),
    ]
