# Generated by Django 4.1.3 on 2023-05-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descansa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='status',
            field=models.CharField(blank=True, choices=[('act', 'active'), ('inc', 'inactive'), ('del', 'delete')], max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('act', 'active'), ('inc', 'inactive'), ('del', 'delete')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bookreading',
            name='status',
            field=models.CharField(blank=True, choices=[('act', 'active'), ('inc', 'inactive'), ('del', 'delete')], max_length=10),
        ),
        migrations.AlterField(
            model_name='readingstatus',
            name='current_status',
            field=models.CharField(blank=True, choices=[('10', 'started'), ('11', 'halfway or more'), ('12', 'finished'), ('13', 'cancelled'), ('14', 'paused'), ('15', 'restarted'), ('21', 'planned')], max_length=16),
        ),
        migrations.AlterField(
            model_name='readingstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('act', 'active'), ('inc', 'inactive'), ('del', 'delete')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.CharField(blank=True, choices=[('act', 'active'), ('inc', 'inactive'), ('del', 'delete')], max_length=10),
        ),
    ]
