# Generated by Django 4.1.3 on 2023-05-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descansa', '0002_alter_author_slug_alter_author_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('created_on',)},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='updated_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='created_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='updated_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='created_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='bookreading',
            old_name='updated_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='bookreading',
            old_name='created_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='readingstatus',
            old_name='updated_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='readingstatus',
            old_name='created_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='updated_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='created_at',
            new_name='updated_on',
        ),
    ]
